
services:
  grafana-ch:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - clickhouse
    networks: [demo]

  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info --brokers=redpanda:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    depends_on: []
    networks: [demo]

  redpanda-console:
    image: redpandadata/console:latest
    environment:
      - KAFKA_BROKERS=redpanda:9092
      - REDPANDA_ADMIN_API=http://redpanda:9644
    ports:
      - "8080:8080"
    depends_on:
      - redpanda
    networks: [demo]

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native TCP
    environment:
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=chpass
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./clickhouse/cors.xml:/etc/clickhouse-server/config.d/cors.xml:ro
    networks: [demo]

  tabix:
    image: spoonest/clickhouse-tabix-web-client:latest
    environment:
      - CH_HOST=clickhouse
      - CH_PORT=8123
      - CH_LOGIN=default
      - CH_PASSWORD=chpass
      - CH_PARAMS=protocol=http
    ports:
      - "8081:80"
    depends_on:
      - clickhouse
    networks: [demo]

networks:
  demo: {}